development:
    history_skip_fields:
      - 'id'
      - 'created_at'
      - 'updated_at'
    attachment_base_path: "#{Rails.root}/public/system/attachments_pratica/"

test:
    history_skip_fields:
      - 'id'
      - 'created_at'
      - 'updated_at'
    attachment_base_path: "attachments"
