development:
    history_skip_fields:
      - 'id'
      - 'created_at'
      - 'updated_at'
    attachment_base_path: "public/system/metadata_attachments"
    attachment_base_url: "/system/metadata_attachments"
    streamables:
      - 'note'
      - 'attachment'

test:
    history_skip_fields:
      - 'id'
      - 'created_at'
      - 'updated_at'
    attachment_base_path: "public/system/metadata_attachments"
    attachment_base_url: "/system/metadata_attachments"
    streamables:
      - 'note'
      - 'attachment'
